### ISSUE TITLE
Trying to find when the job finished

### ISSUE THREAD

**Issue by subhasis1990** [mengz0/amqp#1]
Actually i want to use it as a job queue so I put my operation into the  amqp:consume() function.when a element inserted into the queue , it is consumed by amqp:consume() and I will  process it.But I want send a response to the sender that task finished.I am very much new in  lua and amqp. Can you please suggest any solution which will serve my purpose?

**Comment by mengz0** [comment]
amqp:consume is designed for pattern "Publish/Subscribe". I'm assuming you're trying to implement a "RPC" pattern (see https://www.rabbitmq.com/getstarted.html ) is that right?
