### ISSUE TITLE
Example for Publish/Subscribe Method

### ISSUE THREAD

**Issue by ghost** [mengz0/amqp#2]
Hi,

Thanks for your script , its very useful for me...

I need some example ( order of function usage) for ,
     *  declare the exchange 
     *  bind the exchange 
     *  declare the queue 
     *  bind the queue
      * set the callback function.

I hope u will help me..

Thank you.

**Comment by mengz0** [comment]
The code would look like as below. callback function is set by ctx.opts.callback

```local amqp = require "amqp"
local ctx = amqp.new({...})
ctx:connect("a.b.c.d",#)

local res, err = ctx:exchange_declare(ctx)
...
local res, err = ctx:queue_declare(ctx)
...
local res, err = ctx:queue_bind(ctx)
...
```
