### ISSUE TITLE
Possible problem with large messages

### ISSUE THREAD

**Issue by cybermaggedon** [mengz0/amqp#3]
This library works really well in my application and then I occasionally get an error back, always seems to occur on big messages.  In my Lua code, closing and re-opening the connection doesn't resolve the problem, and I just get the same error message back.

On the Lua side, error is...
```
4	[amqp.publish] failed: [wire_body_frame]closed	
```

In the RabbitMQ logs I see...
```
=ERROR REPORT==== 8-May-2018::16:23:14 ===
Error on AMQP connection <0.20779.0> (127.0.0.1:53934 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 1:
operation none caused a connection exception frame_error: "type 3, all octets = <<>>: {frame_too_large,24219917,131064}"
```
In this case, the message body is length 24219917 i.e. around 23MB.

**Comment by cybermaggedon** [comment]
That pull request should fix it.

**Comment by mengz0** [comment]
merged. https://github.com/mengz0/amqp/pull/5
