### ISSUE TITLE
unexpected symbol

### ISSUE THREAD

**Issue by hecko** [mengz0/amqp#6]
```
lua /usr/share/lua/5.1/amqp.lua
lua: /usr/share/lua/5.1/amqp.lua:509: unexpected symbol near ':'
```

installed using luarocks today

running on CentOS 6

```
lua -v
Lua 5.1.4  Copyright (C) 1994-2008 Lua.org, PUC-Rio
```

**Comment by hecko** [comment]
This library requires LuaJIT (as mentioned in docs) and will not run in lua.org

My mistalke. 

Please close the ticket.

**Comment by mengz0** [comment]
yeah. let me know if you have other questions.
